-- Execute this script once in Supabase: SQL Editor > New query.
create table if not exists public.studios (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  whatsapp text,
  deposit_type text not null default 'fixed',
  deposit_value integer not null default 0,
  settings_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.professionals (
  id bigint generated by default as identity primary key,
  studio_id bigint not null references public.studios(id) on delete cascade,
  name text not null, whatsapp text, specialty text, commission_rate integer not null default 0,
  status text not null default 'active' check (status in ('active','inactive')),
  availability_json jsonb not null default '{"days":[1,2,3,4,5,6],"start":"09:00","end":"19:00"}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.services (
  id bigint generated by default as identity primary key,
  studio_id bigint not null references public.studios(id) on delete cascade,
  name text not null, category text not null default 'geral', price_cents integer not null check (price_cents >= 0),
  duration_minutes integer not null check (duration_minutes > 0), image_url text, active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  studio_id bigint not null references public.studios(id) on delete cascade,
  client_name text not null, client_phone text, starts_at timestamptz not null,
  status text not null default 'scheduled' check (status in ('scheduled','confirmed','pending_deposit','completed','cancelled')),
  payment_status text not null default 'pending', professional_id bigint references public.professionals(id),
  service_id bigint references public.services(id), deposit_cents integer not null default 0, notes text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.users (
  id bigint generated by default as identity primary key, studio_id bigint not null references public.studios(id) on delete cascade,
  phone text not null unique, name text, role text not null default 'owner', created_at timestamptz not null default now()
);
create table if not exists public.sessions (
  id bigint generated by default as identity primary key, token text not null unique,
  user_id bigint not null references public.users(id) on delete cascade, expires_at timestamptz not null, created_at timestamptz not null default now()
);
create table if not exists public.otp_challenges (
  id bigint generated by default as identity primary key, phone text not null, code text not null,
  expires_at timestamptz not null, created_at timestamptz not null default now()
);
create table if not exists public.public_testimonials (
  id bigint generated by default as identity primary key, studio_id bigint not null references public.studios(id) on delete cascade,
  client_name text not null, body text not null, rating integer not null default 5 check (rating between 1 and 5),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists appointments_studio_starts_at on public.appointments(studio_id, starts_at);
create index if not exists services_studio_active on public.services(studio_id, active);
create index if not exists public_testimonials_studio_status on public.public_testimonials(studio_id, status, created_at desc);

-- Keep direct REST access closed until application RLS policies are added.
alter table public.studios enable row level security;
alter table public.professionals enable row level security;
alter table public.services enable row level security;
alter table public.appointments enable row level security;
alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.otp_challenges enable row level security;
alter table public.public_testimonials enable row level security;
